version: '3.8'
services:
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"     # Cliente NATS
      - "8222:8222"     # Monitor HTTP (opcional)
      - "6222:6222"     # Cluster interno (opcional)
    volumes:
      - ./nats-data:/data
    command: >
      -js
      -sd /data
      -m 8222
    restart: unless-stopped
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - '5432:5432'
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:latest
    restart: unless-stopped
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - '27017:27017'
  lovify-auth-service:
    container_name: lovify-authentication-service
    build:
      context: lovify-authentication-service
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres-db
      DB_NAME: auth
      DB_PASSWORD: authsvcpwd
      DB_PORT: 5432
      DB_SSL_MODE: disable
      DB_USER: auth_svc
      MIGRATIONS_PATH: /usr/local/database/migrations
      NATS_ENDPOINT: nats://nats:4222
    ports:
      - '8081:8081'
    depends_on:
      - postgres-db
  lovify-user-service:
    container_name: lovify-user-service
    build:
      context: lovify-user-service
      dockerfile: Dockerfile
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
      NATS_URL: nats://nats:4222
      SPOTIFY_OAUTH_CLIENT_ID: f4ed25e807ab4b74b981cd606a75699b
      SPOTIFY_OAUTH_CLIENT_SECRET: 4b8515bf00ed4f67bbcd9a77d7486bdb
      SPOTIFY_OAUTH_REDIRECT_URL: http://127.0.0.1:8080/callback/spotify
      UPLOADS_DIR: /usr/local/uploads
    ports:
      - '8082:8082'
    depends_on:
      - mongodb
  lovify-matching-service:
    container_name: lovify-matching-service
    build:
      context: lovify-matching-service
      dockerfile: Dockerfile
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
      NATS_URL: nats://nats:4222
    ports:
      - '8083:8083'
    depends_on:
      - mongodb
  lovify-messaging-service:
    container_name: lovify-messaging-service
    build:
      context: lovify-messaging-service
      dockerfile: Dockerfile
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
      NATS_URL: nats://nats:4222
    ports:
      - '8084:8084'
    depends_on:
      - mongodb
