version: '3.8'
services:
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"     # Cliente NATS
      - "8222:8222"     # Monitor HTTP (opcional)
      - "6222:6222"     # Cluster interno (opcional)
    volumes:
      - ./nats-data:/data
    command: >
      -js
      -sd /data
      -m 8222
    restart: unless-stopped
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - '5432:5432'
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:latest
    restart: unless-stopped
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - '27017:27017'
  lovify-auth-service:
    container_name: lovify-authentication-service
    build:
      context: lovify-authentication-service
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres-db
      DB_NAME: auth
      DB_PASSWORD: authsvcpwd
      DB_PORT: 5432
      DB_SSL_MODE: disable
      DB_USER: auth_svc
      MIGRATIONS_PATH: /usr/local/database/migrations
    ports:
      - '8081:8081'
    depends_on:
      - postgres-db