// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: grpc/matching-service/matching-service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommendUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        *string                `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendUsersRequest) Reset() {
	*x = RecommendUsersRequest{}
	mi := &file_grpc_matching_service_matching_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendUsersRequest) ProtoMessage() {}

func (x *RecommendUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matching_service_matching_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendUsersRequest.ProtoReflect.Descriptor instead.
func (*RecommendUsersRequest) Descriptor() ([]byte, []int) {
	return file_grpc_matching_service_matching_service_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendUsersRequest) GetUserID() string {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return ""
}

type RecommendUsersResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RecommendedUsersIDs []string               `protobuf:"bytes,1,rep,name=recommendedUsersIDs" json:"recommendedUsersIDs,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RecommendUsersResponse) Reset() {
	*x = RecommendUsersResponse{}
	mi := &file_grpc_matching_service_matching_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendUsersResponse) ProtoMessage() {}

func (x *RecommendUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matching_service_matching_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendUsersResponse.ProtoReflect.Descriptor instead.
func (*RecommendUsersResponse) Descriptor() ([]byte, []int) {
	return file_grpc_matching_service_matching_service_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendUsersResponse) GetRecommendedUsersIDs() []string {
	if x != nil {
		return x.RecommendedUsersIDs
	}
	return nil
}

var File_grpc_matching_service_matching_service_proto protoreflect.FileDescriptor

const file_grpc_matching_service_matching_service_proto_rawDesc = "" +
	"\n" +
	",grpc/matching-service/matching-service.proto\x12\x17lovify_matching_service\"/\n" +
	"\x15RecommendUsersRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\"J\n" +
	"\x16RecommendUsersResponse\x120\n" +
	"\x13recommendedUsersIDs\x18\x01 \x03(\tR\x13recommendedUsersIDs2\x84\x01\n" +
	"\x0fMatchingService\x12q\n" +
	"\x0eRecommendUsers\x12..lovify_matching_service.RecommendUsersRequest\x1a/.lovify_matching_service.RecommendUsersResponseB\x19Z\x17lovify-matching/serviceb\beditionsp\xe8\a"

var (
	file_grpc_matching_service_matching_service_proto_rawDescOnce sync.Once
	file_grpc_matching_service_matching_service_proto_rawDescData []byte
)

func file_grpc_matching_service_matching_service_proto_rawDescGZIP() []byte {
	file_grpc_matching_service_matching_service_proto_rawDescOnce.Do(func() {
		file_grpc_matching_service_matching_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_matching_service_matching_service_proto_rawDesc), len(file_grpc_matching_service_matching_service_proto_rawDesc)))
	})
	return file_grpc_matching_service_matching_service_proto_rawDescData
}

var file_grpc_matching_service_matching_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_matching_service_matching_service_proto_goTypes = []any{
	(*RecommendUsersRequest)(nil),  // 0: lovify_matching_service.RecommendUsersRequest
	(*RecommendUsersResponse)(nil), // 1: lovify_matching_service.RecommendUsersResponse
}
var file_grpc_matching_service_matching_service_proto_depIdxs = []int32{
	0, // 0: lovify_matching_service.MatchingService.RecommendUsers:input_type -> lovify_matching_service.RecommendUsersRequest
	1, // 1: lovify_matching_service.MatchingService.RecommendUsers:output_type -> lovify_matching_service.RecommendUsersResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_matching_service_matching_service_proto_init() }
func file_grpc_matching_service_matching_service_proto_init() {
	if File_grpc_matching_service_matching_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_matching_service_matching_service_proto_rawDesc), len(file_grpc_matching_service_matching_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_matching_service_matching_service_proto_goTypes,
		DependencyIndexes: file_grpc_matching_service_matching_service_proto_depIdxs,
		MessageInfos:      file_grpc_matching_service_matching_service_proto_msgTypes,
	}.Build()
	File_grpc_matching_service_matching_service_proto = out.File
	file_grpc_matching_service_matching_service_proto_goTypes = nil
	file_grpc_matching_service_matching_service_proto_depIdxs = nil
}
