// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: grpc/matching-service/matching-service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Like int32

const (
	Like_UNKNOWN_LIKE Like = 0
	Like_LIKE         Like = 1
	Like_DISLIKE      Like = 2
)

// Enum value maps for Like.
var (
	Like_name = map[int32]string{
		0: "UNKNOWN_LIKE",
		1: "LIKE",
		2: "DISLIKE",
	}
	Like_value = map[string]int32{
		"UNKNOWN_LIKE": 0,
		"LIKE":         1,
		"DISLIKE":      2,
	}
)

func (x Like) Enum() *Like {
	p := new(Like)
	*p = x
	return p
}

func (x Like) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Like) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_matching_service_matching_service_proto_enumTypes[0].Descriptor()
}

func (Like) Type() protoreflect.EnumType {
	return &file_grpc_matching_service_matching_service_proto_enumTypes[0]
}

func (x Like) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Like.Descriptor instead.
func (Like) EnumDescriptor() ([]byte, []int) {
	return file_grpc_matching_service_matching_service_proto_rawDescGZIP(), []int{0}
}

type RecommendUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        *string                `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendUsersRequest) Reset() {
	*x = RecommendUsersRequest{}
	mi := &file_grpc_matching_service_matching_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendUsersRequest) ProtoMessage() {}

func (x *RecommendUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matching_service_matching_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendUsersRequest.ProtoReflect.Descriptor instead.
func (*RecommendUsersRequest) Descriptor() ([]byte, []int) {
	return file_grpc_matching_service_matching_service_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendUsersRequest) GetUserID() string {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return ""
}

type RecommendUsersResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RecommendedUsersIDs []string               `protobuf:"bytes,1,rep,name=recommendedUsersIDs" json:"recommendedUsersIDs,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RecommendUsersResponse) Reset() {
	*x = RecommendUsersResponse{}
	mi := &file_grpc_matching_service_matching_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendUsersResponse) ProtoMessage() {}

func (x *RecommendUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matching_service_matching_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendUsersResponse.ProtoReflect.Descriptor instead.
func (*RecommendUsersResponse) Descriptor() ([]byte, []int) {
	return file_grpc_matching_service_matching_service_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendUsersResponse) GetRecommendedUsersIDs() []string {
	if x != nil {
		return x.RecommendedUsersIDs
	}
	return nil
}

type HandleLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserID    *string                `protobuf:"bytes,1,opt,name=fromUserID" json:"fromUserID,omitempty"`
	ToUserID      *string                `protobuf:"bytes,2,opt,name=toUserID" json:"toUserID,omitempty"`
	Type          *Like                  `protobuf:"varint,3,opt,name=type,enum=lovify_matching_service.Like" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleLikeRequest) Reset() {
	*x = HandleLikeRequest{}
	mi := &file_grpc_matching_service_matching_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleLikeRequest) ProtoMessage() {}

func (x *HandleLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matching_service_matching_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleLikeRequest.ProtoReflect.Descriptor instead.
func (*HandleLikeRequest) Descriptor() ([]byte, []int) {
	return file_grpc_matching_service_matching_service_proto_rawDescGZIP(), []int{2}
}

func (x *HandleLikeRequest) GetFromUserID() string {
	if x != nil && x.FromUserID != nil {
		return *x.FromUserID
	}
	return ""
}

func (x *HandleLikeRequest) GetToUserID() string {
	if x != nil && x.ToUserID != nil {
		return *x.ToUserID
	}
	return ""
}

func (x *HandleLikeRequest) GetType() Like {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Like_UNKNOWN_LIKE
}

type GetMatchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        *string                `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchesRequest) Reset() {
	*x = GetMatchesRequest{}
	mi := &file_grpc_matching_service_matching_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchesRequest) ProtoMessage() {}

func (x *GetMatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matching_service_matching_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchesRequest.ProtoReflect.Descriptor instead.
func (*GetMatchesRequest) Descriptor() ([]byte, []int) {
	return file_grpc_matching_service_matching_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetMatchesRequest) GetUserID() string {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return ""
}

type GetMatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*Match               `protobuf:"bytes,1,rep,name=matches" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchesResponse) Reset() {
	*x = GetMatchesResponse{}
	mi := &file_grpc_matching_service_matching_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchesResponse) ProtoMessage() {}

func (x *GetMatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matching_service_matching_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchesResponse.ProtoReflect.Descriptor instead.
func (*GetMatchesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_matching_service_matching_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetMatchesResponse) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

type Match struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        *string                `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	MatchedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=matchedAt" json:"matchedAt,omitempty"`
	MatchID       *string                `protobuf:"bytes,3,opt,name=matchID" json:"matchID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_grpc_matching_service_matching_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_matching_service_matching_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_grpc_matching_service_matching_service_proto_rawDescGZIP(), []int{5}
}

func (x *Match) GetUserID() string {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return ""
}

func (x *Match) GetMatchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MatchedAt
	}
	return nil
}

func (x *Match) GetMatchID() string {
	if x != nil && x.MatchID != nil {
		return *x.MatchID
	}
	return ""
}

var File_grpc_matching_service_matching_service_proto protoreflect.FileDescriptor

const file_grpc_matching_service_matching_service_proto_rawDesc = "" +
	"\n" +
	",grpc/matching-service/matching-service.proto\x12\x17lovify_matching_service\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"/\n" +
	"\x15RecommendUsersRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\"J\n" +
	"\x16RecommendUsersResponse\x120\n" +
	"\x13recommendedUsersIDs\x18\x01 \x03(\tR\x13recommendedUsersIDs\"\x82\x01\n" +
	"\x11HandleLikeRequest\x12\x1e\n" +
	"\n" +
	"fromUserID\x18\x01 \x01(\tR\n" +
	"fromUserID\x12\x1a\n" +
	"\btoUserID\x18\x02 \x01(\tR\btoUserID\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.lovify_matching_service.LikeR\x04type\"+\n" +
	"\x11GetMatchesRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\"N\n" +
	"\x12GetMatchesResponse\x128\n" +
	"\amatches\x18\x01 \x03(\v2\x1e.lovify_matching_service.MatchR\amatches\"s\n" +
	"\x05Match\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x128\n" +
	"\tmatchedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tmatchedAt\x12\x18\n" +
	"\amatchID\x18\x03 \x01(\tR\amatchID*/\n" +
	"\x04Like\x12\x10\n" +
	"\fUNKNOWN_LIKE\x10\x00\x12\b\n" +
	"\x04LIKE\x10\x01\x12\v\n" +
	"\aDISLIKE\x10\x022\xbd\x02\n" +
	"\x0fMatchingService\x12q\n" +
	"\x0eRecommendUsers\x12..lovify_matching_service.RecommendUsersRequest\x1a/.lovify_matching_service.RecommendUsersResponse\x12P\n" +
	"\n" +
	"HandleLike\x12*.lovify_matching_service.HandleLikeRequest\x1a\x16.google.protobuf.Empty\x12e\n" +
	"\n" +
	"GetMatches\x12*.lovify_matching_service.GetMatchesRequest\x1a+.lovify_matching_service.GetMatchesResponseB\x19Z\x17lovify-matching/serviceb\beditionsp\xe8\a"

var (
	file_grpc_matching_service_matching_service_proto_rawDescOnce sync.Once
	file_grpc_matching_service_matching_service_proto_rawDescData []byte
)

func file_grpc_matching_service_matching_service_proto_rawDescGZIP() []byte {
	file_grpc_matching_service_matching_service_proto_rawDescOnce.Do(func() {
		file_grpc_matching_service_matching_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_matching_service_matching_service_proto_rawDesc), len(file_grpc_matching_service_matching_service_proto_rawDesc)))
	})
	return file_grpc_matching_service_matching_service_proto_rawDescData
}

var file_grpc_matching_service_matching_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_matching_service_matching_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_matching_service_matching_service_proto_goTypes = []any{
	(Like)(0),                      // 0: lovify_matching_service.Like
	(*RecommendUsersRequest)(nil),  // 1: lovify_matching_service.RecommendUsersRequest
	(*RecommendUsersResponse)(nil), // 2: lovify_matching_service.RecommendUsersResponse
	(*HandleLikeRequest)(nil),      // 3: lovify_matching_service.HandleLikeRequest
	(*GetMatchesRequest)(nil),      // 4: lovify_matching_service.GetMatchesRequest
	(*GetMatchesResponse)(nil),     // 5: lovify_matching_service.GetMatchesResponse
	(*Match)(nil),                  // 6: lovify_matching_service.Match
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 8: google.protobuf.Empty
}
var file_grpc_matching_service_matching_service_proto_depIdxs = []int32{
	0, // 0: lovify_matching_service.HandleLikeRequest.type:type_name -> lovify_matching_service.Like
	6, // 1: lovify_matching_service.GetMatchesResponse.matches:type_name -> lovify_matching_service.Match
	7, // 2: lovify_matching_service.Match.matchedAt:type_name -> google.protobuf.Timestamp
	1, // 3: lovify_matching_service.MatchingService.RecommendUsers:input_type -> lovify_matching_service.RecommendUsersRequest
	3, // 4: lovify_matching_service.MatchingService.HandleLike:input_type -> lovify_matching_service.HandleLikeRequest
	4, // 5: lovify_matching_service.MatchingService.GetMatches:input_type -> lovify_matching_service.GetMatchesRequest
	2, // 6: lovify_matching_service.MatchingService.RecommendUsers:output_type -> lovify_matching_service.RecommendUsersResponse
	8, // 7: lovify_matching_service.MatchingService.HandleLike:output_type -> google.protobuf.Empty
	5, // 8: lovify_matching_service.MatchingService.GetMatches:output_type -> lovify_matching_service.GetMatchesResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grpc_matching_service_matching_service_proto_init() }
func file_grpc_matching_service_matching_service_proto_init() {
	if File_grpc_matching_service_matching_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_matching_service_matching_service_proto_rawDesc), len(file_grpc_matching_service_matching_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_matching_service_matching_service_proto_goTypes,
		DependencyIndexes: file_grpc_matching_service_matching_service_proto_depIdxs,
		EnumInfos:         file_grpc_matching_service_matching_service_proto_enumTypes,
		MessageInfos:      file_grpc_matching_service_matching_service_proto_msgTypes,
	}.Build()
	File_grpc_matching_service_matching_service_proto = out.File
	file_grpc_matching_service_matching_service_proto_goTypes = nil
	file_grpc_matching_service_matching_service_proto_depIdxs = nil
}
